#!/usr/bin/python
#<<<hp_ux_physical_disks>>>
#Internal  1I   1   1  0x4815162342481516  252.5 GB   OK
#Internal  1I   1   2  0x2281488133742069  252.5 GB   OK
#<<<hp_ux_physical_disks_total>>>
#Status_ciss9               = OK

def inventory_hp_ux_physical_disks_total(info):
    inventory = []
    for disk_name, trash, status in info:
            inventory.append((disk_name, None))
    return inventory


def check_hp_ux_physical_disks_total(item, opt, info):
    for disk_name, trash, status in info:
        if item==disk_name:
            if status=='OK':
                return 0, 'All OK with disk.'
            else:
                return 2, 'The disk probably corrupted! Status is not OK!'
    return 2, "Disk not found! Probably disk dead! Check it!"


check_info["hp_ux_physical_disks_total"] = {
    'check_function':          check_hp_ux_physical_disks_total,
    'inventory_function':      inventory_hp_ux_physical_disks_total,
    'service_description':     'Total %s',
}
