#!/usr/bin/python
def inventory_hp_ux_physical_disks_total(info):
    inventory = []
    for disk_name, trash, status in info:
            inventory.append((disk_name, None))
    return inventory


def check_hp_ux_physical_disks_total(item, opt, info):
    for disk_name, trash, status in info:
        if item==disk_name:
            if status=='OK':
                return 0, 'All OK with disk.'
            else:
                return 2, 'The disk probably corrupted! Status is not OK!'
    return 2, "Disk not found! Probably disk dead! Check it!"


check_info["hp_ux_physical_disks_total"] = {
    'check_function':          check_hp_ux_physical_disks_total,
    'inventory_function':      inventory_hp_ux_physical_disks_total,
    'service_description':     'Total %s',
}
