#!/usr/bin/python

def inventory_hp_ux_raid_check(info):
    inventory = []
    for line in info:
        if line[0].startswith('Internal'):
            inventory.append((line[4], None))
        if line[0].startswith('/dev'):
            inventory.append((line[0], None))
    return inventory

def check_hp_ux_raid(item, opt, info):
    for line in info:
        if line[0].startswith('timestamp'):
            last_check_interval=(int(time.time())-int(line[1]))/60
        elif line[0].startswith('Internal'):
            if item == line[4]:
                if line[7] =='OK':
                    return 0, 'disk size: {size} {measure}'.format(size=line[5], measure=line[6])
                else:
                    return 2, 'disk status is not OK! Probably some disk is corrupted! Status: {status}'.format(status=' '.join(line[7:]))
        elif line[0].startswith('/dev'):
            if item == line[0]:
                if last_check_interval > 100:
                    return 2, 'Can not collect fresh data from server. Last successfully check was {min} min. ago'.format(min=last_check_interval)
                elif line[2] == 'OK':
                    return 0, 'all fine with RAID controller'
                else:
                    return 2, 'RAID controller status: {status}'.format(status=' '.join(line[2:]))
    return 2, "Device is not found! Check it!"

check_info["hp_ux_raid_check"] = {
    'check_function':          check_hp_ux_raid,
    'inventory_function':      inventory_hp_ux_raid_check,
    'service_description':     'HW Raid %s status',
}
