#!/usr/bin/python

#weblogic_memory_utilization_default_levels = (80.0, 90.0)

def inventory_weblogic_memory_utilization(info):
    return [(None, None)]

def check_weblogic_memory_utilization(_no_item, params, info):
        infotext = "Heap memory is used on " + str(100-int(info[0][0])) + '%'
        used_percent=100-int(info[0][0])
        if used_percent >=95:
           return (2, infotext, [('Heap used', used_percent)])
        elif used_percent >= 90:
            return (1, infotext, [('Heap used', used_percent)])
        else:
            return (0, infotext, [('Heap used', used_percent)])
        return (3, "UNKNOWN")

check_info["weblogic_heap"] = {
    "check_function"        : check_weblogic_memory_utilization,
    "inventory_function"    : inventory_weblogic_memory_utilization,
    "service_description"   : "Heap free percent:",
    "has_perfdata"          : True,
    "group"                 : "weblogic",
#    "snmp_scan_function"    : lambda oid: "oracle" in oid(".1.3.6.1.4.1.140.625.302.1.41.16.49.122.126.90.155.133.93.134.34.115.99.220.167.216.40.147").lower(),
    "snmp_info"             : ( ".1.3.6.1.4.1.140.625.302.1", ['50'] ),
}
