#!/usr/bin/python

weblogic_memory_utilization_default_levels = (90,95)

def inventory_weblogic_memory_utilization(info):
    if info:
        return [(None, 'weblogic_memory_utilization_default_levels')]

def check_weblogic_memory_utilization(_no_item, params, info):
    if info:
        used_percent = 100-int(info[0][0])
        infotext = "Heap memory is used on {used_percent}%".format(used_percent=used_percent)
        used_percent = 100-int(info[0][0])
        warn, crit = params
        if used_percent >= crit:
           return (2, infotext, [('Heap used', used_percent, warn, crit, 0, 100)])
        elif used_percent >= warn:
           return (1, infotext, [('Heap used', used_percent, warn, crit, 0, 100)])
        else:
           return (0, infotext, [('Heap used', used_percent, warn, crit, 0, 100)])

check_info["weblogic_heap"] = {
    "check_function"        : check_weblogic_memory_utilization,
    "inventory_function"    : inventory_weblogic_memory_utilization,
    "service_description"   : "Weblogic heap free percent",
    "has_perfdata"          : True,
    "group"                 : "weblogic",
    "snmp_info"             : ( ".1.3.6.1.4.1.140.625.302.1", ['50'] ),
}
