#!/usr/bin/python

#weblogic_memory_utilization_default_levels = (80.0, 90.0)

def inventory_weblogic_memory_utilization(info):
    return [(None, None)]

def check_weblogic_memory_utilization(items, params, info):
        free_percent=info[0]
        infotext = "frre persent:"+str(free_percent)
        if free_percent <= 10:
           return (2, "CRIT" + infotext)
        elif free_percent <= 15:
            return (1, "WARN" + infotext)
        else:
            return (0, "OK" + infotext)
        return (3, "UNKNOWN")

check_info["weblogic_heap"] = {
    "check_function"        : check_weblogic_memory_utilization,
    "inventory_function"    : inventory_weblogic_memory_utilization,
    "service_description"   : "Heap free percent:",
    "has_perfdata"          : False,
    "group"                 : "weblogic",
#    "snmp_scan_function"    : lambda oid: "oracle" in oid(".1.3.6.1.4.1.140.625.302.1.41.16.49.122.126.90.155.133.93.134.34.115.99.220.167.216.40.147").lower(),
    "snmp_info"             : ( ".1.3.6.1.4.1.140.625.302.1", ['50'] ),
}
